version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "This is Test"

  staging:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Staging
          command: |
            echo "This is staging"

  production:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Production
          command: |
            echo "This is production"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - staging:
          requires:
            - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - production:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
