version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "This is Test"

  staging:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Staging
          command: |
            echo "This is staging"

  production:
    docker:
      - image: circleci/node:7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Production
          command: |
            echo "This is production"

  notify_manual_approval:
    docker:
      - image: dhoeric/alpine-curl:3.7

    steps:
      - run:
          command: |
            curl \
              -X POST \
              -H 'Content-type: application/json' \
              --data "{\"text\": \"[${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}] Please approve deploy from <https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}|here>. [<${CIRCLE_COMPARE_URL}|diff>]\"}" \
              $SLACK_WEBHOOK_URL_DEPLOY_APPROVE

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - staging:
          requires:
            - test
          filters:
            branches:
              only: master

  # Run only in git tag
  release:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - notify_manual_approval:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - notify_manual_approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - production:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
